"""
Blog router — simple static-HTML pages, one per post.

We don't ship a markdown library as a runtime dep (rule #9 in CLAUDE.md).
The canonical source of each post lives in docs/blog/*.md; the HTML here
is a hand-polished render of that source. When a second post ships, lift
this out to a generic renderer.
"""

from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

from app.config import get_settings


router = APIRouter()


POST_01_TITLE = "Building AutomateEdge Solo — A Free, AI-Curated Learning Platform"
POST_01_DESCRIPTION = (
    "Why AutomateEdge exists, how it's built, and what I'd do differently. "
    "An honest post-mortem of a solo-built AI learning platform — FastAPI, "
    "SQLite, 7 AI providers, HMAC-signed certificates, and a gamified leaderboard."
)
POST_01_PUBLISHED = "2026-04-13"


POST_01_BODY = """
<h1>Building AutomateEdge Solo</h1>
<p class="lede">A free, self-paced platform that gives anyone a personalised,
AI-curated study plan to learn modern AI from scratch — then tracks their
progress, grades their practice repos, and hands them a verifiable
certificate.</p>

<p>This is the honest version of the story. What I built, why I built it
that way, what I got wrong, and what I'd do differently if I started again
tomorrow.</p>

<h2>Why this exists</h2>
<p>The AI learning content that already exists falls into two buckets.</p>
<p>Static roadmaps (roadmap.sh, Coursera landing pages) are one-size-fits-all
and drift within a quarter. The thing at the top of the "you should learn
this first" list is rarely the thing you should learn first in April 2026.
Nobody maintains them.</p>
<p>Paid cohort programs solve the currency problem but gate-keep on price and
schedule. If you work a full-time job and live in a timezone where the live
sessions fall at 2 AM, you are not the target.</p>
<p>AutomateEdge sits between them. The curriculum is generated by AI from
trending signals (university course catalogues, practitioner blogs, arXiv
categories), gets re-evaluated every quarter, and is free. Learners enrol,
get a 3–12 month plan tailored to their level and goal, link their practice
repos as they build, and graduate with a signed credential they can show a
recruiter.</p>

<h2>The stack</h2>
<p>FastAPI + SQLAlchemy 2.0 async + SQLite, a vanilla-JS frontend with no
framework, and seven AI providers on a fallback chain with Gemini Flash 2.5
as the primary.</p>
<p>Every one of those choices is a boring choice for the same reason: this is
a solo project running on one VPS, and every layer I don't add is one fewer
thing I have to keep alive at 2 AM.</p>
<p><strong>SQLite over Postgres.</strong> ~10 active users at launch, maybe
1,000 next year. SQLite handles that with its feet up. The entire database is
one file I can rsync off the server in a second. The day I need row-level
concurrency for more than a few hundred writes per second, I'll switch. That
day is not today.</p>
<p><strong>Vanilla JS over React.</strong> The app is forms + fetch + a few
DOM updates. The original tracker was one static HTML file that worked
offline. Every feature since has been progressive enhancement on top of that.
I can read the entire frontend in one sitting. No bundler, no transpile step,
no <code>npm audit</code> surprises.</p>
<p><strong>Seven AI providers on a chain.</strong> Gemini Flash 2.5 first
(fast, cheap, and I have paid credits), then Groq → Cerebras → Mistral →
DeepSeek → Sambanova → Anthropic. The chain matters because free tiers
rate-limit aggressively and one provider being down shouldn't take the app
down. A circuit breaker skips providers that have failed recently; a
cost-cap gate refuses calls that would exceed a per-day $ budget. OpenAI is
strictly embeddings-only (topic dedup) — the quality-per-dollar at that tier
doesn't justify adding it to the generation chain.</p>

<h2>The AI quality pipeline</h2>
<p>The thing I'm most glad I built is the quality pipeline, because it made
the generated content not-embarrassing.</p>
<p>Every AI-generated template runs through:
<strong>generate → review → refine → validate → score</strong>. The score is
a weighted composite across 15 heuristic dimensions — Bloom's progression,
theory/practice ratio, project density, assessment quality, completeness,
freshness, prerequisites clarity, and so on. Most of the dimensions are
regex + structural checks (zero AI cost); a handful call out to the Gemini
2.5 Pro refiner for deep rewrites of weak weeks.</p>
<p>Templates that score ≥90 are <em>publishable</em>, not <em>published</em>.
That distinction used to be "auto-publish if ≥90", and that's how
AutomateEdge put a confidently-wrong 91-scoring curriculum in front of users
for about two days. From session 9, every auto-generated template lands as a
draft. An admin has to click Publish manually, and that action stamps
<code>last_reviewed_by</code> and <code>last_reviewed_on</code> into
<code>_meta.json</code>. Human in the loop, by policy. The scoring rubric is
a filter, not a judge.</p>

<h2>The certificate system</h2>
<p>The certificate is the emotional payoff. A learner finishes all tasks,
links their repos, and gets a PDF with their name, the course title, their
stats, an HMAC-signed credential ID, a QR code pointing at the public verify
page, and an OpenGraph image they can share on LinkedIn.</p>
<p>The HMAC signing is the important part. The credential ID looks like
<code>AER-2604-abc12-def34</code>, and the final chunk is an HMAC-SHA256 over
the user ID, course key, and issue date, truncated to 8 hex chars. A
recruiter can paste the ID at <code>/verify/&lt;id&gt;</code> and the server
re-derives the HMAC from the database row — if it matches, the credential
is genuine. If someone hand-crafts an ID, the HMAC won't match. The secret
is separate from the JWT secret so we can rotate cert signatures without
invalidating sessions.</p>
<p>PDF rendering goes through WeasyPrint. The first shipped build crashed on
every render because WeasyPrint 62.3 has an incompatibility with pydyf 0.11
that only triggers on certain layouts; pinning weasyprint to 63.1 and pydyf
to 0.11 fixed it. This is the kind of thing you only discover by running
the thing in prod.</p>

<h2>The leaderboard (gamification, done seriously)</h2>
<p>The leaderboard started as a CSV-export nice-to-have and grew into the
single highest-engagement page on the site.</p>
<p>It ranks learners by XP:
<code>tasks × 10 + distinct_repos × 50 + streak_weeks × 20 + cert_bonus</code>,
where cert_bonus is 500 / 750 / 1000 for completion / distinction / honors.
Seven tiers (Apprentice 🥚 → AI Guru 🧙), each with a colored chip and a
mini XP-bar to the next tier. Achievement pills for milestones (First Task,
Triple Crown, 10-week Hot Streak). Distinct repos, not repo-links — same
repo linked to multiple weeks counts once, so you can't farm XP by
re-linking. Last-active recency with a color code (green ≤ 48h, amber ≤ 1w,
muted older).</p>
<p>All of this is derived from real database state. No fake numbers, no
placeholder users, no manual curation. If the leaderboard says you're Top
5%, you are.</p>

<h2>What I'd do differently</h2>
<p><strong>Auto-publish.</strong> I'd never have shipped it. The "quality
score is above the threshold, so obviously it's fine" assumption is exactly
the class of mistake the threshold was supposed to prevent. Every generation
pipeline needs a human gate by default, even if the gate is just "this
person clicked a button".</p>
<p><strong>More integration tests earlier.</strong> The unit tests stayed
green through three weeks of drift in the migrate-progress endpoint
(server-wins logic was refactored, the unit test was still asserting the
old response shape, the endpoint in prod had been quietly broken for the
migrate path since session 6). Session 9 finally added a real end-to-end
journey test. That should have been test #1, not test #104.</p>
<p><strong>Settled on Gemini 2.5 Pro for refinement sooner.</strong> I spent
weeks on Claude + batch API + prompt caching before accepting that for the
refinement workload specifically, Gemini Pro was the right tool. Sticking
with the "Claude is smarter, therefore Claude is better" gut for weeks past
the point I had evidence otherwise cost me both time and money.</p>

<h2>What's next</h2>
<ul>
  <li>An admin UI for revoking certificates (currently DB-edit only).</li>
  <li>A recent-activity stream on the leaderboard, and rank-change arrows so
  learners can see their trajectory.</li>
  <li>An AI news feed and an AI jobs board — the "learn AI, then what" gap
  is the thing I get the most questions about from learners who are
  finishing their first course.</li>
  <li>More templates beyond the three generalist tracks. The quality
  pipeline is good enough now that the bottleneck is the publish-button
  click, not the generation.</li>
</ul>

<h2>If you're thinking of doing something similar</h2>
<p>Ship the boring version first. The first version of the tracker worked
offline, in one HTML file, and that constraint made every later decision
easier — progressive enhancement is a much nicer place to start from than
"let's refactor the frontend".</p>
<p>Build the observability before you need it. An admin dashboard with cost
caps + balance tracking + per-provider alerts is not a premature
optimisation when you're solo and your budget is $10 at each provider. It's
the difference between catching a runaway call pattern at $1 and
discovering it at $10.</p>
<p>And write the post-mortem at the end of every working session, even if
nobody reads it except the next session of yourself.</p>

<hr>
<p class="meta">
  <strong>Source code:</strong>
  <a href="https://github.com/manishjnv/AIExpert" rel="noopener">github.com/manishjnv/AIExpert</a><br>
  <strong>Live site:</strong>
  <a href="https://automateedge.cloud">automateedge.cloud</a><br>
  <strong>Contact:</strong> Open the footer → Contact. The form goes through
  Resend, and I read everything.
</p>
"""


_BLOG_CSS = """
<style>
  :root { color-scheme: dark; }
  body {
    margin: 0; background: #0f1419; color: #e8e4d8;
    font-family: Georgia, 'Times New Roman', serif;
    line-height: 1.7; font-size: 17px;
  }
  main {
    max-width: 720px; margin: 0 auto;
    padding: 48px 24px 96px;
  }
  .meta-line {
    color: #94a3b8; font-family: ui-monospace, SFMono-Regular, monospace;
    font-size: 12px; text-transform: uppercase; letter-spacing: 0.1em;
    margin-bottom: 32px;
  }
  h1 {
    font-family: 'Fraunces', Georgia, serif;
    font-size: clamp(28px, 5vw, 42px); line-height: 1.15;
    color: #f5f1e8; margin: 0 0 24px; font-weight: 700;
  }
  h2 {
    font-family: 'Fraunces', Georgia, serif;
    font-size: 24px; color: #e8a849; margin: 48px 0 12px;
  }
  p { margin: 0 0 16px; }
  .lede { font-size: 19px; color: #d0cbc2; font-style: italic; }
  code {
    background: #1d242e; padding: 1px 6px; border-radius: 3px;
    font-size: 0.9em; color: #e8a849;
    font-family: ui-monospace, SFMono-Regular, 'Cascadia Mono', monospace;
  }
  a { color: #e8a849; text-decoration: underline; text-underline-offset: 3px; }
  a:hover { color: #f5c06a; }
  ul { padding-left: 22px; margin: 0 0 16px; }
  li { margin-bottom: 6px; }
  hr { border: 0; border-top: 1px solid #2a323d; margin: 48px 0 24px; }
  .meta { color: #94a3b8; font-size: 15px; }
  strong { color: #f5f1e8; }
  /* Navbar compat */
  body > nav { font-family: system-ui, -apple-system, sans-serif; }
</style>
"""


def _render_post(slug: str, title: str, description: str, body_html: str, published: str) -> str:
    settings = get_settings()
    base = settings.public_base_url.rstrip("/")
    url = f"{base}/blog/{slug}"
    og_image = f"{base}/assets/og-default.png"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title} — AutomateEdge</title>
  <meta name="description" content="{description}">
  <meta name="author" content="Manish Kumar">

  <!-- Open Graph -->
  <meta property="og:type" content="article">
  <meta property="og:title" content="{title}">
  <meta property="og:description" content="{description}">
  <meta property="og:url" content="{url}">
  <meta property="og:site_name" content="AutomateEdge">
  <meta property="og:image" content="{og_image}">
  <meta property="article:published_time" content="{published}T00:00:00Z">
  <meta property="article:author" content="Manish Kumar">
  <meta property="article:section" content="Build in Public">

  <!-- Twitter Card -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{title}">
  <meta name="twitter:description" content="{description}">
  <meta name="twitter:image" content="{og_image}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fraunces:wght@600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/nav.css">
  {_BLOG_CSS}
</head>
<body>
  <main>
    <div class="meta-line">Published {published} · Manish Kumar · Build in Public</div>
    {body_html}
  </main>
  <script src="/nav.js" defer></script>
</body>
</html>"""


@router.get("/blog/01", response_class=HTMLResponse)
@router.get("/blog/01/", response_class=HTMLResponse)
async def post_01() -> HTMLResponse:
    html = _render_post(
        slug="01",
        title=POST_01_TITLE,
        description=POST_01_DESCRIPTION,
        body_html=POST_01_BODY,
        published=POST_01_PUBLISHED,
    )
    return HTMLResponse(html)
