"""initial schema — all tables from DATA_MODEL.md

Revision ID: 21561aa48ef3
Revises: 
Create Date: 2026-04-10 09:09:24.011746

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21561aa48ef3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_health',
    sa.Column('template_key', sa.String(), nullable=False),
    sa.Column('week_num', sa.Integer(), nullable=False),
    sa.Column('resource_idx', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('last_status', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link_health', schema=None) as batch_op:
        batch_op.create_index('ix_link_health_template_week', ['template_key', 'week_num'], unique=False)

    op.create_table('otp_codes',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index('ix_otp_codes_email', ['email'], unique=False)
        batch_op.create_index('ix_otp_codes_expires_at', ['expires_at'], unique=False)

    op.create_table('plan_versions',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('changes_json', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('github_username', sa.String(), nullable=True),
    sa.Column('learning_goal', sa.String(length=200), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_seen_version', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_provider_id', ['provider_id'], unique=False)

    op.create_table('curriculum_proposals',
    sa.Column('source_run', sa.String(), nullable=False),
    sa.Column('proposal_md', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curriculum_proposals', schema=None) as batch_op:
        batch_op.create_index('ix_curriculum_proposals_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_curriculum_proposals_status', ['status'], unique=False)

    op.create_table('sessions',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_user_id', ['user_id'], unique=False)

    op.create_table('user_plans',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_key', sa.String(), nullable=False),
    sa.Column('plan_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_plans', schema=None) as batch_op:
        batch_op.create_index('ix_user_plans_user_id', ['user_id'], unique=False)

    op.create_table('progress',
    sa.Column('user_plan_id', sa.Integer(), nullable=False),
    sa.Column('week_num', sa.Integer(), nullable=False),
    sa.Column('check_idx', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_plan_id'], ['user_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_plan_id', 'week_num', 'check_idx', name='uq_progress_plan_week_check')
    )
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_index('ix_progress_user_plan_id', ['user_plan_id'], unique=False)

    op.create_table('repo_links',
    sa.Column('user_plan_id', sa.Integer(), nullable=False),
    sa.Column('week_num', sa.Integer(), nullable=False),
    sa.Column('repo_owner', sa.String(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('last_commit_sha', sa.String(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_plan_id'], ['user_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_plan_id', 'week_num', name='uq_repo_links_plan_week')
    )
    op.create_table('evaluations',
    sa.Column('repo_link_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths_json', sa.Text(), nullable=False),
    sa.Column('improvements_json', sa.Text(), nullable=False),
    sa.Column('deliverable_met', sa.Boolean(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['repo_link_id'], ['repo_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_evaluations_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_evaluations_repo_link_id', ['repo_link_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluations_repo_link_id')
        batch_op.drop_index('ix_evaluations_created_at')

    op.drop_table('evaluations')
    op.drop_table('repo_links')
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_index('ix_progress_user_plan_id')

    op.drop_table('progress')
    with op.batch_alter_table('user_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_user_plans_user_id')

    op.drop_table('user_plans')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_id')

    op.drop_table('sessions')
    with op.batch_alter_table('curriculum_proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_curriculum_proposals_status')
        batch_op.drop_index('ix_curriculum_proposals_created_at')

    op.drop_table('curriculum_proposals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_provider_id')

    op.drop_table('users')
    op.drop_table('plan_versions')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_otp_codes_expires_at')
        batch_op.drop_index('ix_otp_codes_email')

    op.drop_table('otp_codes')
    with op.batch_alter_table('link_health', schema=None) as batch_op:
        batch_op.drop_index('ix_link_health_template_week')

    op.drop_table('link_health')
    # ### end Alembic commands ###
