#!/usr/bin/env python3
"""
generate_roadmap_scaffold.py — SEO-04 + SEO-05

Regenerate two auto-generated regions inside frontend/index.html:

1. The crawler-visible SSR scaffold (SEO-04) inside <main id="content">:

       <!-- SCAFFOLD:START (auto) -->
       ...24 week <section> blocks...
       <!-- SCAFFOLD:END -->

2. Three JSON-LD blocks in <head> (SEO-05) — Course, ItemList, FAQPage —
   emitted as separate <script type="application/ld+json"> elements (not
   @graph), matching the pattern Coursera / edX ship:

       <!-- JSONLD:START (auto) -->
       <script type="application/ld+json">...</script>  (Course)
       <script type="application/ld+json">...</script>  (ItemList)
       <script type="application/ld+json">...</script>  (FAQPage)
       <!-- JSONLD:END -->

Both regions read from the same `const DATA = [...]` source of truth.
Run after any DATA edit. Idempotent — re-running with no DATA change is
a no-op on disk.

Usage:
    python scripts/generate_roadmap_scaffold.py          # write in place
    python scripts/generate_roadmap_scaffold.py --check  # exit 1 on drift
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from html import escape
from pathlib import Path

FRONTEND = Path(__file__).resolve().parent.parent / "frontend" / "index.html"

START_MARK = "<!-- SCAFFOLD:START (auto-generated by scripts/generate_roadmap_scaffold.py — do not edit by hand) -->"
END_MARK = "<!-- SCAFFOLD:END -->"
MAIN_EMPTY = '<main id="content"></main>'
MAIN_OPEN = '<main id="content">'

JSONLD_START = "<!-- JSONLD:START (auto-generated by scripts/generate_roadmap_scaffold.py — do not edit by hand) -->"
JSONLD_END = "<!-- JSONLD:END -->"

SITE_URL = "https://automateedge.cloud"
ORG_NAME = "AutomateEdge"
LOGO_URL = f"{SITE_URL}/assets/logo.png"
COURSE_IMAGE = f"{SITE_URL}/og/course/generalist.png"

# Learning outcomes surfaced in Google's "What you'll learn" panel.
# Harvested from the six monthly phases + responsible-AI + capstone.
# Each string must be ≤120 chars (Google truncates longer entries).
TEACHES: list[str] = [
    "Python, NumPy, Pandas, SQL, and Jupyter for hands-on data exploration",
    "Linear algebra, probability, and statistics as applied to machine learning",
    "Classical ML with scikit-learn — feature engineering, trees, boosting, clustering, and time series",
    "Deep learning with PyTorch — CNNs for vision and transformers for language, trained from scratch",
    "LLM application building — prompts, RAG, vector databases, agents, tool use, and evaluation",
    "MLOps fundamentals — FastAPI services, Docker containers, and cloud deployment on AWS",
    "Responsible AI practices and first open-source contribution to a real ML project",
    "End-to-end capstone: design, build, deploy, document, and publish an AI application",
]

COURSE_PREREQUISITES = (
    "Basic Python familiarity and high-school algebra. No CS degree required."
)

# 12 Q&A pairs covering the queries surfaced in the SERP recon (docs/SEO.md §3.5).
# Each answer is 80-110 words — long enough to qualify for the FAQ rich snippet,
# short enough to fit Google's display cap. Do not extend past 120 words.
FAQ: list[tuple[str, str]] = [
    (
        "How long does the AI roadmap take?",
        "The full plan spans 24 weeks at roughly 8 hours per week — about 200 hours total across 6 months. That pace assumes you're holding down a job or full course load in parallel. If you can commit 15+ hours per week, many learners finish in 14-16 weeks. If life gets in the way, Week 20 is a built-in buffer week, and the plan is structured so you can pause and resume without losing context. The pace is a recommendation, not a deadline — what matters is finishing the capstone, not finishing on time.",
    ),
    (
        "Is it really free?",
        "Yes. Every resource linked in the 24-week plan is free to access — Kaggle Learn, Stanford CS231n, 3Blue1Brown, fast.ai, Hugging Face, official PyTorch and scikit-learn documentation, and Andrew Ng's ML Specialization, which is auditable for free on Coursera. There is no paywall, no paid upgrade, no premium tier. Progress tracking saves to your browser or to your free account. Sharing milestones on LinkedIn is free. AI-powered repository evaluations use free-tier APIs. No credit card is ever required, and you can complete the entire plan without spending a single dollar.",
    ),
    (
        "Do I need a CS degree?",
        "No. The roadmap is designed for career changers and self-taught developers as much as for CS graduates. The only prerequisites are basic Python comfort — loops, functions, dictionaries — and high-school algebra. Weeks 1 and 2 explicitly refresh these if you're rusty. Many learners who complete the plan are working engineers from other fields, bootcamp graduates, or domain experts transitioning into AI. What matters is consistent weekly effort, not a specific academic background. Employers hiring AI generalists increasingly weight shipped projects and public portfolios over credentials on paper.",
    ),
    (
        "How is this different from roadmap.sh or Coursera?",
        "Roadmap.sh shows you a static tree of topics but gives you no time estimates, no weekly deliverables, no way to track progress, and no feedback on your work. Coursera offers structured courses but they're siloed — you have to stitch together your own sequence, and meaningful certificates cost money. This plan is a concrete 24-week schedule with weekly deliverables, curated free resources, a tracker that saves your progress, GitHub integration that evaluates your practice work with AI, and quarterly refreshes so the curriculum stays current. It's opinionated on purpose — one sensible path, not a maze of choices.",
    ),
    (
        "How current is the content?",
        "The curriculum is refreshed every quarter — roughly every three months — by pulling trending topics from Stanford, MIT, and other top universities, plus practitioner sources like Hugging Face and leading AI labs. When a new technique becomes important (for example, agents and tool use were added in the most recent refresh), it gets folded into the right week. The refresh is driven by an automated pipeline that surfaces drift and a human reviewer who approves additions. A version badge near the page title shows when the plan was last updated.",
    ),
    (
        "Can I get a certificate?",
        "Yes. Each major milestone — completing a month, shipping the capstone, finishing all 24 weeks — issues a verifiable credential you can share on LinkedIn. The credential links back to a public verification page on this site that shows what you completed and when, so anyone reviewing your profile can confirm it's real. The certificates are free. They're not a replacement for an industry certification like AWS AI Practitioner or Google Cloud ML Engineer, but they signal demonstrated commitment and give you a portfolio-linked artifact to share with recruiters and hiring managers.",
    ),
    (
        "What if I fall behind?",
        "The plan bakes in a buffer. Week 20 is explicitly a catch-up week — no new material is assigned, so you can clear backlog, retry a project you weren't happy with, or rest. If you fall further behind, you can pause the tracker and resume from exactly where you left off. Many learners stretch the plan to 8 or 10 months without losing anything. The goal is consistent progress, not a specific finish date. Falling behind is not a failure mode — skipping weeks entirely or quitting is. Most finishers take a break at some point.",
    ),
    (
        "How much math do I need?",
        "Less than most people fear. The roadmap requires high-school algebra and basic statistics going in — that's the floor. Week 2 covers the essentials you'll actually use: linear algebra (vectors, matrices, dot products via 3Blue1Brown), probability and Bayes, calculus intuition for gradient descent, and hypothesis testing. You won't need to derive backpropagation from scratch, but you will need to read it and follow along. If you've finished a first-year university calculus or statistics course, you're already past the bar. If not, Week 2 is a serious refresher, not a survey.",
    ),
    (
        "Do I need a GPU?",
        "No — not to complete the roadmap. Every deep-learning exercise can run on Google Colab's free GPU tier, Kaggle Notebooks (free T4 GPUs), or Hugging Face Spaces. For the LLM and transformer weeks, you'll use hosted APIs (Anthropic, OpenAI, Hugging Face Inference) that don't require local compute at all. If you want to train larger models or run many experiments in parallel, a personal GPU is a nice-to-have, but the plan is deliberately designed so no learner is blocked by hardware. Free cloud compute is genuinely enough to finish every week.",
    ),
    (
        "What if I already know Python?",
        "Skim Week 1 — confirm you're fluent in Pandas, NumPy, and SQL (most self-taught developers are weaker on SQL than they think). If Week 1 feels trivial, go to Week 2 and test yourself on the statistics refresher. If that's also trivial, jump to Week 3 or Week 5 directly. The plan's \"NEW\" markers flag content that changed in the last quarterly refresh — check those even in areas you think you know. Experienced developers typically finish the plan in 14-18 weeks instead of 24, and spend the saved time on a more ambitious capstone.",
    ),
    (
        "Do I need to know machine learning to start?",
        "No. The roadmap assumes zero prior machine-learning experience and builds from first principles. Weeks 3 and 4 introduce supervised learning, evaluation, and the ML vocabulary. By Month 2 you're doing feature engineering and building tree-based models. By Month 3 you're writing neural networks in PyTorch. If you're already comfortable with classical ML — say you've completed Andrew Ng's ML Specialization — the plan gives you credit for that: skim Weeks 3-8 and start at Week 9 with deep learning. No one is penalized for starting ahead, and no one is left behind for starting cold.",
    ),
    (
        "What kind of job does this prepare me for?",
        "AI generalist, machine-learning engineer (junior to mid-level), ML platform engineer, applied AI engineer, or AI-focused software engineer. The plan covers the full stack — data exploration, classical ML, deep learning, LLMs and RAG, MLOps, and cloud deployment — so you're not pigeonholed into one niche. If you want to go deeper on a specialization (computer vision research, ML infrastructure, or RLHF fine-tuning), the capstone in Month 6 is the right place to do that, and the portfolio you build makes the case to an employer. Shipped projects increasingly outweigh credentials in hiring decisions.",
    ),
]


def _extract_data_literal(html: str) -> str:
    """Return the `[...]` text of `const DATA = [ ... ];`, bracket-balanced."""
    m = re.search(r"const\s+DATA\s*=\s*\[", html)
    if not m:
        raise RuntimeError("Could not find `const DATA = [` in frontend/index.html")
    start = m.end() - 1
    depth, i, in_str, escaped = 0, start, None, False
    while i < len(html):
        ch = html[i]
        if in_str:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == in_str:
                in_str = None
        else:
            if ch in ('"', "'"):
                in_str = ch
            elif ch == "[":
                depth += 1
            elif ch == "]":
                depth -= 1
                if depth == 0:
                    return html[start : i + 1]
        i += 1
    raise RuntimeError("Unterminated DATA array literal")


def _js_to_json(src: str) -> str:
    """Best-effort JS-object-literal → JSON normalizer.

    Tokenizes string-vs-code regions so key-quoting and trailing-comma stripping
    only touch code. Handles double-quoted strings as-is; rewrites single-quoted
    strings to JSON (defensive — current DATA uses only double quotes).
    """
    parts: list[tuple[bool, str]] = []  # (is_string, text)
    i, n = 0, len(src)
    while i < n:
        ch = src[i]
        if ch in ('"', "'"):
            quote = ch
            j = i + 1
            while j < n:
                if src[j] == "\\":
                    j += 2
                    continue
                if src[j] == quote:
                    break
                j += 1
            raw = src[i : j + 1]
            if quote == "'":
                inner = raw[1:-1].replace("\\'", "'").replace("\\\\", "\\")
                raw = json.dumps(inner, ensure_ascii=False)
            parts.append((True, raw))
            i = j + 1
        else:
            k = i
            while k < n and src[k] not in ('"', "'"):
                k += 1
            parts.append((False, src[i:k]))
            i = k

    out = []
    for is_str, text in parts:
        if is_str:
            out.append(text)
            continue
        text = re.sub(r'([{,]\s*)([A-Za-z_][A-Za-z0-9_]*)\s*:', r'\1"\2":', text)
        text = re.sub(r",(\s*[\]}])", r"\1", text)
        out.append(text)
    return "".join(out)


def _load_data(html: str) -> list[dict]:
    literal = _extract_data_literal(html)
    return json.loads(_js_to_json(literal))


def _week_description(week: dict) -> str:
    deliv = week.get("deliv") or []
    focus = week.get("focus") or []
    if deliv:
        joined = ". ".join(s.rstrip(".") for s in deliv if s)
        return joined + ("." if joined and not joined.endswith(".") else "")
    if focus:
        return focus[0]
    return ""


def _render_scaffold(data: list[dict]) -> str:
    lines = [
        START_MARK,
        '  <section data-roadmap-scaffold>',
        "    <h1>24-Week AI Generalist Roadmap</h1>",
        "    <p>Free, self-paced path from Python fundamentals to deployed AI applications. "
        "Six monthly phases, 24 weeks, curated resources from Stanford, MIT, "
        "Kaggle, Hugging Face, and leading practitioners. No signup, no paywall.</p>",
    ]
    week_count = 0
    for month in data:
        m_num = month.get("month", "?")
        m_label = escape(month.get("label", ""))
        m_title = escape(month.get("title", ""))
        tagline = escape(month.get("tagline", ""))
        lines.append(
            f"    <p><strong>Month {m_num} — {m_label}:</strong> {m_title}</p>"
        )
        if tagline:
            lines.append(f"    <p>{tagline}</p>")
        for week in month.get("weeks", []):
            n = week["n"]
            title = escape(week.get("t", ""))
            desc = escape(_week_description(week))
            resources = week.get("resources") or []
            items = "".join(
                f"        <li>{escape(r.get('name', ''))}</li>\n"
                for r in resources[:5]
                if r.get("name")
            )
            lines.append(f'    <section id="week-{n}">')
            lines.append(f"      <h2>Week {n}: {title}</h2>")
            lines.append(f"      <p>{desc}</p>")
            lines.append("      <ul>")
            # items already has trailing newlines; strip the final one for join
            lines.append(items.rstrip("\n"))
            lines.append("      </ul>")
            lines.append("    </section>")
            week_count += 1
    lines.append("  </section>")
    lines.append(f"  {END_MARK}")

    if week_count != 24:
        raise RuntimeError(f"Expected 24 weeks, scaffold built {week_count}")
    return "\n".join(lines)


def _flatten_weeks(data: list[dict]) -> list[dict]:
    weeks: list[dict] = []
    for month in data:
        for w in month.get("weeks", []):
            weeks.append(w)
    return weeks


def _build_course(data: list[dict]) -> dict:
    weeks = _flatten_weeks(data)
    syllabus = [
        {
            "@type": "Syllabus",
            "name": f"Week {w['n']}: {w.get('t', '')}",
            "description": _week_description(w) or w.get("t", ""),
            "timeRequired": "PT8H",
        }
        for w in weeks
    ]
    has_part = [
        {
            "@type": "Course",
            "@id": f"{SITE_URL}/#week-{w['n']}",
            "name": f"Week {w['n']}: {w.get('t', '')}",
        }
        for w in weeks
    ]
    return {
        "@context": "https://schema.org",
        "@type": "Course",
        "name": "AI Generalist Roadmap — 24-Week Interactive Study Plan",
        "description": (
            "Free, self-paced 24-week roadmap to become an AI generalist. "
            "Covers Python, math, classical ML, deep learning with PyTorch, LLMs, "
            "RAG, agents, and MLOps. Personalized by AI, refreshed quarterly with "
            "trending topics from top universities and practitioner sources."
        ),
        "url": f"{SITE_URL}/",
        "image": COURSE_IMAGE,
        "inLanguage": "en",
        "educationalLevel": "Beginner to Intermediate",
        "provider": {
            "@type": "Organization",
            "name": ORG_NAME,
            "sameAs": SITE_URL,
            "logo": {"@type": "ImageObject", "url": LOGO_URL},
        },
        "offers": [
            {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "USD",
                "category": "Free",
            }
        ],
        "teaches": list(TEACHES),
        "coursePrerequisites": COURSE_PREREQUISITES,
        "hasCourseInstance": {
            "@type": "CourseInstance",
            "courseMode": "Online",
            "courseWorkload": "PT200H",
            "instructor": {"@type": "Organization", "name": ORG_NAME},
        },
        "syllabusSections": syllabus,
        "hasPart": has_part,
    }


def _build_itemlist(data: list[dict]) -> dict:
    weeks = _flatten_weeks(data)
    return {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": "24-Week AI Roadmap — Weekly Modules",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": w["n"],
                "url": f"{SITE_URL}/#week-{w['n']}",
                "name": f"Week {w['n']}: {w.get('t', '')}",
            }
            for w in weeks
        ],
    }


def _build_faqpage() -> dict:
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": q,
                "acceptedAnswer": {"@type": "Answer", "text": a},
            }
            for q, a in FAQ
        ],
    }


def _jsonld_safe(obj: dict) -> str:
    """Serialize to JSON-LD safe for embedding in a <script> element.

    Escapes `</` → `<\\/` (valid JSON per the spec's optional `\\/` escape) so
    no value can prematurely terminate the <script> element. indent=2 keeps
    regenerated diffs readable.
    """
    s = json.dumps(obj, ensure_ascii=False, indent=2)
    return s.replace("</", "<\\/")


def _validate_jsonld(course: dict, itemlist: dict, faq: dict) -> None:
    """Enforce SEO-05 acceptance constraints at generation time."""
    n_syllabus = len(course["syllabusSections"])
    if n_syllabus != 24:
        raise RuntimeError(f"Course.syllabusSections must have 24 entries, got {n_syllabus}")
    n_has_part = len(course["hasPart"])
    if n_has_part != 24:
        raise RuntimeError(f"Course.hasPart must have 24 entries, got {n_has_part}")
    n_items = len(itemlist["itemListElement"])
    if n_items != 24:
        raise RuntimeError(f"ItemList.itemListElement must have 24 entries, got {n_items}")
    for i, t in enumerate(course["teaches"]):
        if len(t) > 120:
            raise RuntimeError(f"teaches[{i}] is {len(t)} chars (>120): {t!r}")
    if len(course["coursePrerequisites"]) > 200:
        raise RuntimeError(
            f"coursePrerequisites is {len(course['coursePrerequisites'])} chars (>200)"
        )
    for i, q in enumerate(faq["mainEntity"]):
        words = len(q["acceptedAnswer"]["text"].split())
        if not (40 <= words <= 120):
            raise RuntimeError(
                f"FAQ[{i}] answer has {words} words, must be 40-120: {q['name']!r}"
            )


def _render_jsonld(data: list[dict]) -> str:
    course = _build_course(data)
    itemlist = _build_itemlist(data)
    faq = _build_faqpage()
    _validate_jsonld(course, itemlist, faq)
    blocks = [
        f'<script type="application/ld+json">\n{_jsonld_safe(course)}\n</script>',
        f'<script type="application/ld+json">\n{_jsonld_safe(itemlist)}\n</script>',
        f'<script type="application/ld+json">\n{_jsonld_safe(faq)}\n</script>',
    ]
    return "\n".join([JSONLD_START, *blocks, JSONLD_END])


def _inject_scaffold(html: str, scaffold: str) -> str:
    pattern = re.compile(
        re.escape(START_MARK) + r".*?" + re.escape(END_MARK),
        re.DOTALL,
    )
    if pattern.search(html):
        return pattern.sub(scaffold, html)
    if MAIN_EMPTY in html:
        return html.replace(MAIN_EMPTY, f"{MAIN_OPEN}\n{scaffold}\n</main>")
    # Fallback: inject inside an already-expanded <main id="content"> block
    return re.sub(
        r'(<main id="content">)(\s*)',
        lambda m: f"{m.group(1)}\n{scaffold}\n",
        html,
        count=1,
    )


def _inject_jsonld(html: str, block: str) -> str:
    pattern = re.compile(
        re.escape(JSONLD_START) + r".*?" + re.escape(JSONLD_END),
        re.DOTALL,
    )
    if pattern.search(html):
        return pattern.sub(block, html)
    # First run: insert before </head>. Match only the first (real) </head> —
    # later `</head>` strings live inside JS-string HTML templates for PDF
    # export and must not be touched.
    return html.replace("</head>", f"{block}\n</head>", 1)


def _inject(html: str, scaffold: str, jsonld: str) -> str:
    html = _inject_scaffold(html, scaffold)
    html = _inject_jsonld(html, jsonld)
    return html


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the scaffold on disk is out of sync with DATA",
    )
    args = ap.parse_args()

    html = FRONTEND.read_text(encoding="utf-8")
    data = _load_data(html)
    scaffold = _render_scaffold(data)
    jsonld = _render_jsonld(data)
    new_html = _inject(html, scaffold, jsonld)

    if args.check:
        if new_html != html:
            print(
                "Scaffold/JSON-LD drift detected. Run: python scripts/generate_roadmap_scaffold.py",
                file=sys.stderr,
            )
            return 1
        print("Scaffold + JSON-LD up to date (24 weeks).")
        return 0

    FRONTEND.write_text(new_html, encoding="utf-8")
    print(
        f"Regenerated: scaffold {len(scaffold)} bytes, JSON-LD {len(jsonld)} bytes "
        f"(24 weeks, 12 FAQs, 8 teaches)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
