#!/usr/bin/env python3
"""
generate_roadmap_scaffold.py — SEO-04

Regenerate the crawler-visible SSR scaffold inside frontend/index.html.

Reads the inline `const DATA = [...]` roadmap (source of truth for the
24-week default plan) and emits a <section data-roadmap-scaffold> block
between these marker comments inside <main id="content">:

    <!-- SCAFFOLD:START (auto) -->
    ...24 week <section> blocks...
    <!-- SCAFFOLD:END -->

Run after any DATA edit. Idempotent — re-running with no DATA change is
a no-op on disk (writes the same bytes back).

Usage:
    python scripts/generate_roadmap_scaffold.py          # write in place
    python scripts/generate_roadmap_scaffold.py --check  # exit 1 on drift
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from html import escape
from pathlib import Path

FRONTEND = Path(__file__).resolve().parent.parent / "frontend" / "index.html"

START_MARK = "<!-- SCAFFOLD:START (auto-generated by scripts/generate_roadmap_scaffold.py — do not edit by hand) -->"
END_MARK = "<!-- SCAFFOLD:END -->"
MAIN_EMPTY = '<main id="content"></main>'
MAIN_OPEN = '<main id="content">'


def _extract_data_literal(html: str) -> str:
    """Return the `[...]` text of `const DATA = [ ... ];`, bracket-balanced."""
    m = re.search(r"const\s+DATA\s*=\s*\[", html)
    if not m:
        raise RuntimeError("Could not find `const DATA = [` in frontend/index.html")
    start = m.end() - 1
    depth, i, in_str, escaped = 0, start, None, False
    while i < len(html):
        ch = html[i]
        if in_str:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == in_str:
                in_str = None
        else:
            if ch in ('"', "'"):
                in_str = ch
            elif ch == "[":
                depth += 1
            elif ch == "]":
                depth -= 1
                if depth == 0:
                    return html[start : i + 1]
        i += 1
    raise RuntimeError("Unterminated DATA array literal")


def _js_to_json(src: str) -> str:
    """Best-effort JS-object-literal → JSON normalizer.

    Tokenizes string-vs-code regions so key-quoting and trailing-comma stripping
    only touch code. Handles double-quoted strings as-is; rewrites single-quoted
    strings to JSON (defensive — current DATA uses only double quotes).
    """
    parts: list[tuple[bool, str]] = []  # (is_string, text)
    i, n = 0, len(src)
    while i < n:
        ch = src[i]
        if ch in ('"', "'"):
            quote = ch
            j = i + 1
            while j < n:
                if src[j] == "\\":
                    j += 2
                    continue
                if src[j] == quote:
                    break
                j += 1
            raw = src[i : j + 1]
            if quote == "'":
                inner = raw[1:-1].replace("\\'", "'").replace("\\\\", "\\")
                raw = json.dumps(inner, ensure_ascii=False)
            parts.append((True, raw))
            i = j + 1
        else:
            k = i
            while k < n and src[k] not in ('"', "'"):
                k += 1
            parts.append((False, src[i:k]))
            i = k

    out = []
    for is_str, text in parts:
        if is_str:
            out.append(text)
            continue
        text = re.sub(r'([{,]\s*)([A-Za-z_][A-Za-z0-9_]*)\s*:', r'\1"\2":', text)
        text = re.sub(r",(\s*[\]}])", r"\1", text)
        out.append(text)
    return "".join(out)


def _load_data(html: str) -> list[dict]:
    literal = _extract_data_literal(html)
    return json.loads(_js_to_json(literal))


def _week_description(week: dict) -> str:
    deliv = week.get("deliv") or []
    focus = week.get("focus") or []
    if deliv:
        joined = ". ".join(s.rstrip(".") for s in deliv if s)
        return joined + ("." if joined and not joined.endswith(".") else "")
    if focus:
        return focus[0]
    return ""


def _render_scaffold(data: list[dict]) -> str:
    lines = [
        START_MARK,
        '  <section data-roadmap-scaffold>',
        "    <h1>24-Week AI Generalist Roadmap</h1>",
        "    <p>Free, self-paced path from Python fundamentals to deployed AI applications. "
        "Six monthly phases, 24 weeks, curated resources from Stanford, MIT, "
        "Kaggle, Hugging Face, and leading practitioners. No signup, no paywall.</p>",
    ]
    week_count = 0
    for month in data:
        m_num = month.get("month", "?")
        m_label = escape(month.get("label", ""))
        m_title = escape(month.get("title", ""))
        tagline = escape(month.get("tagline", ""))
        lines.append(
            f"    <p><strong>Month {m_num} — {m_label}:</strong> {m_title}</p>"
        )
        if tagline:
            lines.append(f"    <p>{tagline}</p>")
        for week in month.get("weeks", []):
            n = week["n"]
            title = escape(week.get("t", ""))
            desc = escape(_week_description(week))
            resources = week.get("resources") or []
            items = "".join(
                f"        <li>{escape(r.get('name', ''))}</li>\n"
                for r in resources[:5]
                if r.get("name")
            )
            lines.append(f'    <section id="week-{n}">')
            lines.append(f"      <h2>Week {n}: {title}</h2>")
            lines.append(f"      <p>{desc}</p>")
            lines.append("      <ul>")
            # items already has trailing newlines; strip the final one for join
            lines.append(items.rstrip("\n"))
            lines.append("      </ul>")
            lines.append("    </section>")
            week_count += 1
    lines.append("  </section>")
    lines.append(f"  {END_MARK}")

    if week_count != 24:
        raise RuntimeError(f"Expected 24 weeks, scaffold built {week_count}")
    return "\n".join(lines)


def _inject(html: str, scaffold: str) -> str:
    pattern = re.compile(
        re.escape(START_MARK) + r".*?" + re.escape(END_MARK),
        re.DOTALL,
    )
    if pattern.search(html):
        return pattern.sub(scaffold, html)
    if MAIN_EMPTY in html:
        return html.replace(MAIN_EMPTY, f"{MAIN_OPEN}\n{scaffold}\n</main>")
    # Fallback: inject inside an already-expanded <main id="content"> block
    return re.sub(
        r'(<main id="content">)(\s*)',
        lambda m: f"{m.group(1)}\n{scaffold}\n",
        html,
        count=1,
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the scaffold on disk is out of sync with DATA",
    )
    args = ap.parse_args()

    html = FRONTEND.read_text(encoding="utf-8")
    data = _load_data(html)
    scaffold = _render_scaffold(data)
    new_html = _inject(html, scaffold)

    if args.check:
        if new_html != html:
            print(
                "Scaffold drift detected. Run: python scripts/generate_roadmap_scaffold.py",
                file=sys.stderr,
            )
            return 1
        print("Scaffold up to date (24 weeks).")
        return 0

    FRONTEND.write_text(new_html, encoding="utf-8")
    print(f"Scaffold regenerated: 24 weeks, {len(scaffold)} bytes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
